"""汇总三平台冒烟测试结果 -> verified.json + environment.yml。

规则:三个平台全部通过,才更新「已验证版本」和锁定的 environment.yml;
任何一个失败,保留上次通过的版本,只把这次的失败记进 last_run / history。

用法: python ci/aggregate.py <结果目录> [--run-url URL] [--allow-partial]
--allow-partial 只用于本地首次生成(只有一个平台的结果时)。
"""
import datetime as dt
import glob
import json
import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
VERIFIED = os.path.join(ROOT, "verified.json")
ENV_YML = os.path.join(ROOT, "environment.yml")
REQUIRED = ["Linux", "macOS", "Windows"]

# 发行名 -> conda 包名(锁定文件里要用 conda 的名字)
CONDA = {
    "python": "python", "numpy": "numpy", "scipy": "scipy", "pandas": "pandas", "h5py": "h5py",
    "scikit-learn": "scikit-learn", "matplotlib": "matplotlib", "mne": "mne-base",
    "pyriemann": "pyriemann", "torch": "pytorch", "torchaudio": "torchaudio",
    "jupyterlab": "jupyterlab", "ipykernel": "ipykernel",
}
PIP = ["braindecode", "moabb"]
KEY = ["mne", "braindecode", "moabb", "torch"]


def main():
    args = sys.argv[1:]
    res_dir = args[0]
    run_url = args[args.index("--run-url") + 1] if "--run-url" in args else None
    partial = "--allow-partial" in args

    results = {}
    for p in sorted(glob.glob(os.path.join(res_dir, "*.json"))):
        with open(p, encoding="utf-8") as f:
            r = json.load(f)
        r["versions"]["python"] = r["python"]
        results[r["os"]] = r

    today = dt.datetime.now(dt.timezone.utc).strftime("%Y-%m-%d")
    wanted = sorted(results) if partial else REQUIRED

    per_os = {}
    for o in wanted:
        r = results.get(o)
        if r is None:
            per_os[o] = {"passed": False, "missing": True}
            continue
        per_os[o] = {
            "passed": r["passed"], "device": r.get("device"), "python": r["python"],
            "elapsed": r.get("elapsed"),
            "failed": [t["name"] + (": " + t["detail"] if t["detail"] else "")
                       for t in r["tests"] if t["status"] == "FAIL"],
        }
    all_pass = bool(per_os) and all(v["passed"] for v in per_os.values())

    data = {}
    if os.path.exists(VERIFIED):
        with open(VERIFIED, encoding="utf-8") as f:
            data = json.load(f)

    data["last_run"] = {"date": today, "run_url": run_url, "passed": all_pass, "os": per_os}

    if all_pass:
        names = sorted({k for r in results.values() for k in r["versions"]})
        versions = {}
        for n in names:
            vals = sorted({r["versions"].get(n) for r in results.values() if r["versions"].get(n)})
            if vals:
                versions[n] = vals[0] if len(vals) == 1 else {o: results[o]["versions"].get(n) for o in results}
        data["verified"] = {
            "date": today, "run_url": run_url, "platforms": sorted(results),
            "devices": {o: results[o].get("device") for o in results},
            "versions": versions,
        }
        write_env_yml(versions, today, sorted(results))

    hist = data.get("history", [])
    hist.insert(0, {
        "date": today, "passed": all_pass, "run_url": run_url,
        "os": {o: v["passed"] for o, v in per_os.items()},
        "key": {k: next((r["versions"].get(k) for r in results.values() if r["versions"].get(k)), None) for k in KEY},
    })
    data["history"] = hist[:20]

    with open(VERIFIED, "w", encoding="utf-8") as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")
    print("all passed" if all_pass else "NOT all passed — kept previous verified versions")
    for o, v in per_os.items():
        print(f"  {o:<8} {'PASS' if v['passed'] else 'FAIL'}  {'; '.join(v.get('failed', [])) or ''}")


def pin(v, pip=False):
    """单一版本 -> 精确锁定;各平台不一致 -> 给出最小到最大的区间。"""
    eq = "==" if pip else "="
    if isinstance(v, dict):
        vals = sorted({x for x in v.values() if x})
        return f">={vals[0]},<={vals[-1]}"
    return f"{eq}{v}"


def write_env_yml(versions, today, platforms):
    lines = [
        "# BCI 入门环境 / BCI starter environment",
        f"# 已在 {' / '.join(platforms)} 上通过冒烟测试 · verified {today}",
        "# 由 CI 自动生成,请不要手改;要改依赖请改 ci/spec.yml。",
        "# Generated by CI - do not edit by hand; change ci/spec.yml instead.",
        "#",
        "# 用法 / Usage:",
        "#   conda env create -f environment.yml",
        "#   conda activate bci",
        "name: bci",
        "channels:",
        "  - conda-forge",
        "  - nodefaults",
        "dependencies:",
    ]
    for dist, conda_name in CONDA.items():
        if dist in versions:
            lines.append(f"  - {conda_name}{pin(versions[dist])}")
    lines += ["  - pip", "  - pip:"]
    for dist in PIP:
        v = versions.get(dist)
        if v:
            lines.append(f"      - {dist}{pin(v, pip=True)}")
    with open(ENV_YML, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
